module.exports = {
  SENDER_EMAIL: process.env.SENDER_EMAIL,
  SENDER_EMAIL_PASSWORD: process.env.SENDER_EMAIL_PASSWORD,
  USERNAME: process.env.USERNAME,
  PASSWORD: process.env.PASSWORD,
  ACCESS_TOKEN_SECRET: process.env.ACCESS_TOKEN_SECRET,
  ALLOWED_ORIGIN: process.env.ALLOWED_ORIGIN,
  SERVICEACCOUNT: process.env.SERVICEACCOUNT,
};
